# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]

functions = "src/functions/"

command = "yarn build"
publish = "src/functions"